"""
plot_bands.py  --  Band structure plot from Quantum ESPRESSO bands.x output

Usage:
    python plot_bands.py Pt

Output (written to calc/Pt/04_bands/):
    bands_Pt.png  -- Band structure plot with Fermi level marked

Requires:
    calc/Pt/04_bands/bands.dat.gnu   (generated by bands.x)
    calc/Pt/04_bands/bands_pp.out    (generated by bands.x, for tick positions)
    calc/Pt/01_scf/scf.out           (to read Fermi energy)

Notes:
    bands.x outputs two files:
      bands.dat      -- binary eigenvalue data (not used directly)
      bands.dat.gnu  -- plain text: col1 = k-distance, col2 = energy [eV]
                        Bands are separated by blank lines.

    High-symmetry point labels are read from bands.in (K_POINTS crystal_b
    comment fields "! Label"), so they always match the k-path used in the
    calculation regardless of the Bravais lattice type.

    Tick positions are read from bands_pp.out. QE writes either:
      "x coordinate   0.7071"   (older versions)
      "x_coord =  0.7071"       (newer versions)
    Both formats are handled.
"""

import os
import re
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def read_fermi_energy(scf_out_path: str) -> float:
    """Parse the Fermi energy from QE scf.out. Returns the last occurrence."""
    if not os.path.exists(scf_out_path):
        raise FileNotFoundError(f"scf.out not found: {scf_out_path}")

    pattern = re.compile(
        r"the\s+Fermi\s+energy\s+is\s+([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)",
        re.IGNORECASE,
    )
    efermi = None
    with open(scf_out_path) as f:
        for line in f:
            m = pattern.search(line)
            if m:
                efermi = float(m.group(1))
    if efermi is None:
        raise RuntimeError(f"Fermi energy not found in {scf_out_path}")
    return efermi


def parse_bands_gnu(filepath):
    """
    Parse bands.dat.gnu produced by QE bands.x.

    Returns
    -------
    bands : list of np.ndarray, each shape (nk,)  -- energies per band
    k_arr : np.ndarray, shape (nk,)               -- k-path distances
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"bands.dat.gnu not found: {filepath}")

    bands     = []
    k_vals    = []
    e_vals    = []
    k_arr_ref = None

    with open(filepath) as f:
        for raw_line in f:
            line = raw_line.strip()
            if line == "":
                if k_vals:
                    bands.append(np.array(e_vals))
                    if k_arr_ref is None:
                        k_arr_ref = np.array(k_vals)
                    k_vals = []
                    e_vals = []
            else:
                parts = line.split()
                if len(parts) >= 2:
                    k_vals.append(float(parts[0]))
                    e_vals.append(float(parts[1]))

    # Flush last band (no trailing blank line in some QE versions)
    if k_vals:
        bands.append(np.array(e_vals))
        if k_arr_ref is None:
            k_arr_ref = np.array(k_vals)

    if not bands:
        raise RuntimeError(f"No band data found in {filepath}")

    return bands, k_arr_ref


def read_hsym_positions(bands_pp_out_path):
    """
    Extract high-symmetry k-point x-coordinates from bands_pp.out.

    Handles both QE output formats:
      "high-symmetry point: ...   x coordinate   0.7071"  (older)
      "high-symmetry point: ...   x_coord =  0.7071"      (newer)
    """
    if not os.path.exists(bands_pp_out_path):
        return []

    # Match either "x coordinate <val>" or "x_coord = <val>" or "x_coord= <val>"
    pattern = re.compile(
        r"high-symmetry point.*?x[_ ]coord(?:inate)?(?:\s*=)?\s+([\d.]+)",
        re.IGNORECASE,
    )
    positions = []
    with open(bands_pp_out_path) as f:
        for line in f:
            m = pattern.search(line)
            if m:
                positions.append(float(m.group(1)))
    return positions


def read_kpath_labels(bands_in_path):
    """
    Extract ordered high-symmetry point labels from bands.in.

    Reads lines of the form:
        0.50000  0.00000  0.50000    40  ! X
    and returns the label after "!".

    Consecutive identical labels (branch discontinuity, e.g. U then K)
    are collapsed into "U|K".
    """
    if not os.path.exists(bands_in_path):
        return []

    raw_labels = []
    in_kblock  = False
    skip_count = True   # first non-empty line after K_POINTS is the point count

    with open(bands_in_path) as f:
        for line in f:
            if "K_POINTS" in line and "crystal_b" in line:
                in_kblock  = True
                skip_count = True
                continue
            if not in_kblock:
                continue
            stripped = line.strip()
            if not stripped:
                continue
            # Skip the point-count line
            if skip_count and re.match(r"^\d+$", stripped):
                skip_count = False
                continue
            skip_count = False
            m = re.search(r"!\s*(\S+)", line)
            raw_labels.append(m.group(1) if m else "")

    if not raw_labels:
        return []

    # Collapse consecutive equal labels into "A|B"
    labels = [raw_labels[0]]
    for i in range(1, len(raw_labels)):
        if raw_labels[i] == raw_labels[i - 1]:
            labels[-1] = f"{raw_labels[i - 1]}|{raw_labels[i]}"
        else:
            labels.append(raw_labels[i])

    return labels


def format_label(label: str) -> str:
    """Render 'Gamma' or 'G' as LaTeX $\\Gamma$; pass other tokens through."""
    parts = label.split("|")
    rendered = []
    for p in parts:
        if p in ("GAMMA", "Gamma", "G"):
            rendered.append(r"$\Gamma$")
        else:
            rendered.append(p)
    return "|".join(rendered)


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        sys.exit("Usage: python plot_bands.py <Formula>")

    formula   = sys.argv[1]
    ROOT_DIR  = os.path.dirname(os.path.abspath(__file__))
    bands_dir = os.path.join(ROOT_DIR, "calc", formula, "04_bands")
    scf_dir   = os.path.join(ROOT_DIR, "calc", formula, "01_scf")

    gnu_path      = os.path.join(bands_dir, "bands.dat.gnu")
    bands_pp_out  = os.path.join(bands_dir, "bands_pp.out")
    bands_in_path = os.path.join(bands_dir, "bands.in")
    scf_out_path  = os.path.join(scf_dir,   "scf.out")
    out_png       = os.path.join(bands_dir, f"bands_{formula}.png")

    # ---- Parse band data ----
    print(f"Parsing band data: {gnu_path}", flush=True)
    bands, k_arr = parse_bands_gnu(gnu_path)
    print(f"  {len(bands)} bands  x  {len(k_arr)} k-points", flush=True)

    # ---- Fermi energy ----
    print(f"Reading Fermi energy: {scf_out_path}", flush=True)
    efermi = read_fermi_energy(scf_out_path)
    print(f"  E_Fermi = {efermi:.4f} eV", flush=True)

    # ---- Tick positions from bands_pp.out ----
    hsym_positions = read_hsym_positions(bands_pp_out)
    print(f"  High-symmetry positions ({len(hsym_positions)}): {hsym_positions}", flush=True)

    # ---- Labels from bands.in ----
    kpath_labels = read_kpath_labels(bands_in_path)
    print(f"  k-path labels ({len(kpath_labels)}): {kpath_labels}", flush=True)

    # Pair positions with labels
    if hsym_positions:
        hsym_pairs = []
        for i, pos in enumerate(hsym_positions):
            raw = kpath_labels[i] if i < len(kpath_labels) else str(i)
            hsym_pairs.append((pos, format_label(raw)))
    else:
        print("  WARNING: no tick positions found in bands_pp.out", flush=True)
        first = format_label(kpath_labels[0])  if kpath_labels else ""
        last  = format_label(kpath_labels[-1]) if kpath_labels else ""
        hsym_pairs = [(k_arr[0], first), (k_arr[-1], last)]

    print(f"  Tick pairs: {[(f'{p:.4f}', l) for p, l in hsym_pairs]}", flush=True)

    # ---- Plot ----
    fig, ax = plt.subplots(figsize=(7, 6))

    E_window = 3.5   # eV shown above and below the Fermi level

    # Band curves
    for band in bands:
        ax.plot(k_arr, band - efermi,
                color="steelblue", linewidth=0.9, alpha=0.85)

    # Fermi level
    ax.axhline(0.0, color="red", linewidth=1.0, linestyle="--")

    # Vertical lines at every high-symmetry point
    for x, _ in hsym_pairs:
        ax.axvline(x, color="black", linewidth=0.7, linestyle="-")

    # Axis limits and labels
    ax.set_xlim(k_arr[0], k_arr[-1])
    ax.set_ylim(-E_window, E_window)
    ax.set_ylabel("$E - E_F$  (eV)", fontsize=13)
    ax.set_title(f"Band structure of {formula}", fontsize=14)

    # x-axis ticks
    ax.set_xticks([p for p, _ in hsym_pairs])
    ax.set_xticklabels([l for _, l in hsym_pairs], fontsize=12)
    ax.tick_params(axis="x", length=0)   # hide tick marks; labels are enough
    ax.set_xlabel("Wave Vector", fontsize=12)

    # Legend
    ax.legend(handles=[
        Line2D([0], [0], color="steelblue", lw=1.5, label="QE bands"),
        Line2D([0], [0], color="red", lw=1.0, linestyle="--",
               label=f"$E_F$ = {efermi:.4f} eV"),
    ], fontsize=10, loc="upper right")

    ax.grid(True, axis="y", linestyle=":", alpha=0.4)

    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    print(f"Plot saved: {out_png}", flush=True)


if __name__ == "__main__":
    main()