"""
plot_bands.py  --  Band structure plot from Quantum ESPRESSO bands.x output

Usage:
    python plot_bands.py Pt

Output (written to calc/Pt/04_bands/):
    bands_Pt.png  -- Band structure plot with Fermi level marked

Requires:
    calc/Pt/04_bands/bands.dat.gnu   (generated by bands.x)
    calc/Pt/01_scf/scf.out           (to read Fermi energy)

Notes:
    bands.x outputs two files:
      bands.dat      -- binary eigenvalue data (not used directly)
      bands.dat.gnu  -- plain text: col1 = k-distance, col2 = energy [eV]
                        Bands are separated by blank lines.
"""

import os
import re
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def read_fermi_energy(scf_out_path: str) -> float:
    """Parse Fermi energy from QE scf.out (reused from run_shc.py)."""
    if not os.path.exists(scf_out_path):
        raise FileNotFoundError(f"scf.out not found: {scf_out_path}")

    pattern = re.compile(
        r"the\s+Fermi\s+energy\s+is\s+([-+]?\d+\.?\d*(?:[eE][-+]?\d+)?)",
        re.IGNORECASE,
    )
    efermi = None
    with open(scf_out_path) as f:
        for line in f:
            m = pattern.search(line)
            if m:
                efermi = float(m.group(1))
    if efermi is None:
        raise RuntimeError(f"Fermi energy not found in {scf_out_path}")
    return efermi


def parse_bands_gnu(filepath):
    """
    Parse bands.dat.gnu produced by QE bands.x.

    The file contains multiple bands separated by blank lines.
    Each line within a band block: k_distance   energy_eV

    Returns
    -------
    bands : list of np.ndarray, each shape (nk,)  -- energies per band
    k_arr : np.ndarray, shape (nk,)               -- k-path distances
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"bands.dat.gnu not found: {filepath}")

    bands    = []
    k_vals   = []
    e_vals   = []

    with open(filepath) as f:
        for raw_line in f:
            line = raw_line.strip()
            if line == "":
                # Band separator
                if k_vals:
                    bands.append(np.array(e_vals))
                    if len(bands) == 1:
                        k_arr_ref = np.array(k_vals)
                    k_vals = []
                    e_vals = []
            else:
                parts = line.split()
                if len(parts) >= 2:
                    k_vals.append(float(parts[0]))
                    e_vals.append(float(parts[1]))

    # Flush last band (no trailing blank line in some QE versions)
    if k_vals:
        bands.append(np.array(e_vals))
        if len(bands) == 1:
            k_arr_ref = np.array(k_vals)

    if not bands:
        raise RuntimeError(f"No band data found in {filepath}")

    return bands, k_arr_ref


def read_hsym_positions(bands_out_path):
    """
    Extract high-symmetry k-point positions (in k-distance units)
    from bands_pp.out produced by bands.x.

    bands.x prints lines like:
        high-symmetry point:   0.0000  0.0000  0.0000   x_coord =  0.0000
    or:
        high-symmetry point:  0.5000  0.0000  0.5000   x_coord =  0.7071

    Returns list of x_coord values.
    Labels are set to '' because bands.x does not output names; caller
    should override them manually via default_labels below.
    """
    if not os.path.exists(bands_out_path):
        return []

    pattern = re.compile(r"high-symmetry point.*?x_coord\s*=\s*([\d.]+)", re.IGNORECASE)
    positions = []
    with open(bands_out_path) as f:
        for line in f:
            m = pattern.search(line)
            if m:
                positions.append(float(m.group(1)))

    return positions


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        sys.exit("Usage: python plot_bands.py <Formula>")

    formula   = sys.argv[1]
    ROOT_DIR  = os.path.dirname(os.path.abspath(__file__))
    bands_dir = os.path.join(ROOT_DIR, "calc", formula, "04_bands")
    scf_dir   = os.path.join(ROOT_DIR, "calc", formula, "01_scf")

    gnu_path     = os.path.join(bands_dir, "bands.dat.gnu")
    bands_out    = os.path.join(bands_dir, "bands_pp.out")
    scf_out_path = os.path.join(scf_dir,   "scf.out")
    out_png      = os.path.join(bands_dir, f"bands_{formula}.png")

    # ---- Parse data ----
    print(f"Parsing band data: {gnu_path}", flush=True)
    bands, k_arr = parse_bands_gnu(gnu_path)
    nbands = len(bands)
    nk     = len(k_arr)
    print(f"  {nbands} bands  x  {nk} k-points", flush=True)

    # ---- Fermi energy ----
    print(f"Reading Fermi energy from: {scf_out_path}", flush=True)
    efermi = read_fermi_energy(scf_out_path)
    print(f"  Fermi energy: {efermi:.4f} eV", flush=True)

    # ---- High-symmetry positions ----
    hsym_positions = read_hsym_positions(bands_out)
    # Default labels for FCC (Gamma-X-U|K-Gamma-L-W-X).
    # Adjust this list for non-FCC materials.
    default_labels = ["L", "Gamma", "X", "U|K", "K", "Gamma"]
    if hsym_positions:
        # Pair positions with labels (pad with empty string if fewer labels)
        hsym_pairs = [
            (pos, default_labels[i] if i < len(default_labels) else "")
            for i, pos in enumerate(hsym_positions)
        ]
    else:
        # Fall back: place vertical lines at start and end only
        hsym_pairs = [(k_arr[0], ""), (k_arr[-1], "")]

    # ---- Plot ----
    fig, ax = plt.subplots(figsize=(7, 6))

    # Energy window: +-3.5 eV around Fermi level
    E_window = 3.5
    E_min = efermi - E_window
    E_max = efermi + E_window

    # Plot each band shifted so Fermi = 0
    for band in bands:
        ax.plot(k_arr, band - efermi,
                color="steelblue", linewidth=0.9, alpha=0.85)

    # Fermi level
    ax.axhline(0.0, color="red", linewidth=1.0, linestyle="--",
               label=f"$E_F$ = {efermi:.4f} eV")

    # High-symmetry vertical lines
    for x, label in hsym_pairs:
        ax.axvline(x, color="black", linewidth=0.7, linestyle="-")

    # Axis formatting
    ax.set_xlim(k_arr[0], k_arr[-1])
    ax.set_ylim(E_min - efermi, E_max - efermi)
    ax.set_ylabel("$E - E_F$  (eV)", fontsize=13)
    ax.set_title(f"Band structure of {formula}", fontsize=14)

    # Set x-ticks at high-symmetry points with labels
    if hsym_pairs:
        tick_positions = [p for p, _ in hsym_pairs]
        tick_labels    = [
            r"$\Gamma$" if l in ("Gamma", "G") else l
            for _, l in hsym_pairs
        ]
        ax.set_xticks(tick_positions)
        ax.set_xticklabels(tick_labels, fontsize=12)
    else:
        ax.set_xlabel("k-path", fontsize=13)

    # Custom legend
    legend_elements = [
        Line2D([0], [0], color="steelblue", lw=1.5, label="QE bands"),
        Line2D([0], [0], color="red", lw=1.0, linestyle="--",
               label=f"$E_F$ = {efermi:.4f} eV"),
    ]
    ax.legend(handles=legend_elements, fontsize=10, loc="upper right")
    ax.grid(True, axis="y", linestyle=":", alpha=0.4)

    fig.tight_layout()
    fig.savefig(out_png, dpi=150)
    print(f"Plot saved: {out_png}", flush=True)


if __name__ == "__main__":
    main()