"""
plot_charge.py  --  2D cross-section plot of charge density
                    Reads charge.cube (Gaussian cube format) from pp.x

Usage:
    python plot_charge.py Pt

Output (written to calc/Pt/01b_charge/):
    charge_density_Pt.png  -- 2D cross-section plot (z = mid-plane)

Requires:
    calc/Pt/01b_charge/charge.cube   (generated by pp.x)
"""

import os
import sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.colors import LogNorm


# ------------------------------------------------------------------
# Cube file parser
# ------------------------------------------------------------------

def read_cube(filepath):
    """
    Parse a Gaussian cube file.

    Returns
    -------
    data     : np.ndarray, shape (nx, ny, nz)  -- volumetric data
    origin   : np.ndarray, shape (3,)           -- origin in Bohr
    axes     : np.ndarray, shape (3, 3)         -- lattice vectors (row = axis)
    atoms    : list of (Z, x, y, z)             -- atomic positions in Bohr
    """
    with open(filepath) as f:
        lines = f.readlines()

    # Lines 0-1: comments
    # Line 2: natoms  ox  oy  oz
    natoms_line = lines[2].split()
    natoms = int(natoms_line[0])
    origin = np.array([float(x) for x in natoms_line[1:4]])

    # Lines 3-5: nx  ax  ay  az  (voxel count + lattice vector for each axis)
    grid   = []
    axes   = []
    for i in range(3):
        parts = lines[3 + i].split()
        grid.append(int(parts[0]))
        axes.append([float(x) for x in parts[1:4]])
    nx, ny, nz = grid
    axes = np.array(axes)   # shape (3, 3), each row is one axis vector

    # Lines 6..(6+natoms-1): atomic data
    atoms = []
    for i in range(natoms):
        parts = lines[6 + i].split()
        atoms.append((int(parts[0]), float(parts[2]), float(parts[3]), float(parts[4])))

    # Remaining lines: volumetric data (nx * ny * nz values)
    data_start = 6 + natoms
    raw = []
    for line in lines[data_start:]:
        raw.extend([float(x) for x in line.split()])
    data = np.array(raw).reshape(nx, ny, nz)

    return data, origin, axes, atoms


def bohr_to_angstrom(x):
    return x * 0.529177


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        sys.exit("Usage: python plot_charge.py <Formula>")

    formula  = sys.argv[1]
    ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
    charge_dir = os.path.join(ROOT_DIR, "calc", formula, "01b_charge")
    cube_path  = os.path.join(charge_dir, "charge.cube")
    out_png    = os.path.join(charge_dir, f"charge_density_{formula}.png")

    if not os.path.exists(cube_path):
        sys.exit(f"❌ cube file not found: {cube_path}\n"
                 "   Run pp.x (Step 2) first.")

    print(f"Reading cube file: {cube_path}", flush=True)
    data, origin, axes, atoms = read_cube(cube_path)
    nx, ny, nz = data.shape
    print(f"  Grid: {nx} x {ny} x {nz}", flush=True)
    print(f"  Value range: {data.min():.4e} -- {data.max():.4e}", flush=True)

    # ------------------------------------------------------------------
    # Build real-space coordinate grids for the z = mid-plane slice
    # (xy cross-section at z = nz // 2)
    # ------------------------------------------------------------------
    iz = nz // 2   # mid-plane index

    # Axis vectors in Bohr → convert to Angstrom
    a0 = bohr_to_angstrom(axes[0])   # step along x-grid
    a1 = bohr_to_angstrom(axes[1])   # step along y-grid
    ox = bohr_to_angstrom(origin[0])
    oy = bohr_to_angstrom(origin[1])

    # Physical coordinates of each grid point
    i_idx = np.arange(nx)
    j_idx = np.arange(ny)
    X = ox + np.outer(i_idx, a0[0]) + np.outer(j_idx, a1[0]).T   # (ny, nx)
    Y = oy + np.outer(i_idx, a0[1]) + np.outer(j_idx, a1[1]).T

    # Slice: data[ix, iy, iz]  → rearrange to (ny, nx) for imshow
    slice_data = data[:, :, iz].T   # shape (ny, nx)

    # ------------------------------------------------------------------
    # Atomic positions projected onto the xy plane
    # ------------------------------------------------------------------
    atom_x = [bohr_to_angstrom(a[1]) for a in atoms]
    atom_y = [bohr_to_angstrom(a[2]) for a in atoms]
    atom_z = [bohr_to_angstrom(a[3]) for a in atoms]

    # Only show atoms within ±1 Å of the slice plane
    z_slice_angstrom = bohr_to_angstrom(origin[2] + iz * axes[2][2])
    near_atoms = [
        (ax, ay) for ax, ay, az in zip(atom_x, atom_y, atom_z)
        if abs(az - z_slice_angstrom) < 1.0
    ]

    # ------------------------------------------------------------------
    # Plot
    # ------------------------------------------------------------------
    fig, axes_plot = plt.subplots(1, 2, figsize=(13, 5.5))

    xmin, xmax = X.min(), X.max()
    ymin, ymax = Y.min(), Y.max()
    extent = [xmin, xmax, ymin, ymax]

    # ---- Panel 1: Linear scale ----
    ax1 = axes_plot[0]
    im1 = ax1.imshow(
        slice_data,
        origin="lower",
        extent=extent,
        cmap="inferno",
        aspect="equal",
        interpolation="bilinear",
    )
    cb1 = fig.colorbar(im1, ax=ax1, fraction=0.046, pad=0.04)
    cb1.set_label("Charge density  (e/Bohr³)", fontsize=10)
    cb1.ax.yaxis.set_major_formatter(ticker.ScalarFormatter(useMathText=True))
    cb1.ax.ticklabel_format(style="sci", axis="y", scilimits=(0, 0))

    for ax_pt, ay_pt in near_atoms:
        ax1.plot(ax_pt, ay_pt, "o", color="cyan", ms=6, mew=1.5,
                 mec="white", label="atom (projected)")

    ax1.set_xlabel("x  (Å)", fontsize=12)
    ax1.set_ylabel("y  (Å)", fontsize=12)
    ax1.set_title(f"Charge density (linear)\n{formula}  —  z-slice at index {iz}", fontsize=11)
    ax1.set_xlim(xmin, xmax)
    ax1.set_ylim(ymin, ymax)

    # ---- Panel 2: Log scale (reveals low-density regions) ----
    ax2 = axes_plot[1]
    # Guard against zero/negative values before log
    safe_data = np.where(slice_data > 0, slice_data, slice_data[slice_data > 0].min())
    im2 = ax2.imshow(
        safe_data,
        origin="lower",
        extent=extent,
        cmap="viridis",
        aspect="equal",
        interpolation="bilinear",
        norm=LogNorm(vmin=safe_data.min(), vmax=safe_data.max()),
    )
    cb2 = fig.colorbar(im2, ax=ax2, fraction=0.046, pad=0.04)
    cb2.set_label("Charge density  (e/Bohr³)  [log]", fontsize=10)

    for ax_pt, ay_pt in near_atoms:
        ax2.plot(ax_pt, ay_pt, "o", color="red", ms=6, mew=1.5,
                 mec="white")

    ax2.set_xlabel("x  (Å)", fontsize=12)
    ax2.set_ylabel("y  (Å)", fontsize=12)
    ax2.set_title(f"Charge density (log scale)\n{formula}  —  z-slice at index {iz}", fontsize=11)
    ax2.set_xlim(xmin, xmax)
    ax2.set_ylim(ymin, ymax)

    fig.suptitle(f"Electron charge density — {formula}", fontsize=14, y=1.02)
    fig.tight_layout()
    fig.savefig(out_png, dpi=150, bbox_inches="tight")
    print(f"Plot saved: {out_png}", flush=True)


if __name__ == "__main__":
    main()